# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import os
from telegram import *
from telegram.ext import *
from datetime import datetime

TOKEN = os.getenv("TOKEN")

users = {}

# ---------------- القائمة الرئيسية ----------------
def main_menu():
    return ReplyKeyboardMarkup([
        ["📂 حساباتي", "➕ إنشاء حساب"],
        ["💳 تعبئة/سحب", "💰 محفظتي"],
        ["📞 الدعم"]
    ], resize_keyboard=True)

# ---------------- start ----------------
def start(update, context):
    user_id = update.effective_user.id

    if user_id not in users:
        users[user_id] = {
            "wallet": 0,
            "accounts": [],
            "step": None,
            "selected_account": None,
            "history": [],
            "amount": 0,
            "action": None
        }

    update.message.reply_text("👋 أهلا بك", reply_markup=main_menu())

# ---------------- عرض الحسابات ----------------
def show_accounts(update, context):
    user = users[update.effective_user.id]

    if not user["accounts"]:
        update.message.reply_text("❌ لا يوجد حسابات")
        return

    keyboard = [
        [InlineKeyboardButton(acc["username"], callback_data=f"acc_{i}")]
        for i, acc in enumerate(user["accounts"])
    ]

    update.message.reply_text("📂 حساباتك:", reply_markup=InlineKeyboardMarkup(keyboard))

# ---------------- الأزرار ----------------
def button(update, context):
    query = update.callback_query
    user_id = query.from_user.id
    user = users[user_id]
    data = query.data

    query.answer()

    # -------- عرض حساب --------
    if data.startswith("acc_"):
        i = int(data.split("_")[1])
        acc = user["accounts"][i]
        user["selected_account"] = i

        keyboard = [
            [InlineKeyboardButton("❌ حذف", callback_data="delete")],
            [InlineKeyboardButton("🔑 تغيير كلمة السر", callback_data="change_pass")]
        ]

        query.edit_message_text(
            f"👤 {acc['username']}\n🔑 {acc['password']}\n💰 {acc['balance']} ل.س",
            reply_markup=InlineKeyboardMarkup(keyboard)
        )

    elif data == "delete":
        i = user["selected_account"]
        user["accounts"].pop(i)
        query.edit_message_text("✅ تم حذف الحساب")

    elif data == "change_pass":
        user["step"] = "change_pass"
        query.message.reply_text("✏️ اكتب كلمة السر الجديدة:")

    # -------- اختيار حساب --------
    elif data.startswith("select_"):
        i = int(data.split("_")[1])
        user["selected_account"] = i
        user["step"] = "amount_account"
        query.message.reply_text("💰 اكتب المبلغ:")

    # -------- تنفيذ على الحساب --------
    elif data in ["deposit_acc", "withdraw_acc"]:
        i = user["selected_account"]
      amount = user["amount"]

    # ✅ تحديد العملية
    user["action"] = data

    if data == "deposit_acc":
        if user["wallet"] >= amount:
            user["wallet"] -= amount
            user["accounts"][i]["balance"] += amount
            user["history"].append(f"➕ {amount} ل.س إلى الحساب")
            query.message.reply_text("✅ تم التعبئة")
        else:
            query.message.reply_text("❌ الرصيد غير كافي")

    elif data == "withdraw_acc":
        if user["accounts"][i]["balance"] >= amount:
            user["accounts"][i]["balance"] -= amount
            user["wallet"] += amount
            user["history"].append(f"➖ {amount} ل.س إلى المحفظة")
            query.message.reply_text("✅ تم السحب")
        else:
            query.message.reply_text("❌ رصيد الحساب غير كافي")
        i = user["selected_account"]
        amount = user["amount"]

        if data == "deposit_acc":
            if user["wallet"] >= amount:
                user["wallet"] -= amount
                user["accounts"][i]["balance"] += amount
                user["history"].append(f"➕ {amount} ل.س إلى الحساب")
                query.message.reply_text("✅ تم التعبئة")
            else:
                query.message.reply_text("❌ الرصيد غير كافي")

        elif data == "withdraw_acc":
            if user["accounts"][i]["balance"] >= amount:
                user["accounts"][i]["balance"] -= amount
                user["wallet"] += amount
                user["history"].append(f"➖ {amount} ل.س إلى المحفظة")
                query.message.reply_text("✅ تم السحب")
            else:
                query.message.reply_text("❌ رصيد الحساب غير كافي")

    # -------- محفظة --------
    elif data == "deposit_wallet":
        user["step"] = "deposit_wallet"
        query.message.reply_text("💰 أدخل المبلغ:")

    elif data == "withdraw_wallet":
        user["step"] = "withdraw_wallet"
        query.message.reply_text("💰 أدخل المبلغ:")

    elif data == "history":
        logs = user["history"]
        msg = "\n".join(logs[-10:]) if logs else "لا يوجد عمليات"
        query.message.reply_text(msg)

    # -------- طرق الدفع --------
    elif data in ["syriatel", "sham"]:
        amount = user["amount"]
        method = "سيريتيل" if data == "syriatel" else "شام"

        # 🔌 API مكانك هنا
        # requests.post("YOUR_API", json={...})

        if user["action"] == "deposit_wallet":
            user["wallet"] += amount
            user["history"].append(f"➕ {amount} ل.س عبر {method}")
            query.message.reply_text("✅ تم شحن المحفظة")

        elif user["action"] == "withdraw_wallet":
            if user["wallet"] < amount:
                query.message.reply_text("❌ الرصيد غير كافي")
                return

            user["wallet"] -= amount
            user["history"].append(f"➖ {amount} ل.س عبر {method}")
            query.message.reply_text("✅ تم السحب")

# ---------------- الرسائل ----------------
def handle_message(update, context):
    user = users[update.effective_user.id]
    text = update.message.text

    # -------- محفظتي --------
    if text == "💰 محفظتي":
        keyboard = [
            [InlineKeyboardButton("➕ تعبئة المحفظة", callback_data="deposit_wallet")],
            [InlineKeyboardButton("➖ سحب من المحفظة", callback_data="withdraw_wallet")],
            [InlineKeyboardButton("📊 العمليات", callback_data="history")]
        ]

        update.message.reply_text(
            f"💰 رصيدك: {user['wallet']} ل.س",
            reply_markup=InlineKeyboardMarkup(keyboard)
        )

    # -------- حساباتي --------
    elif text == "📂 حساباتي":
        show_accounts(update, context)

    # -------- إنشاء حساب --------
    elif text == "➕ إنشاء حساب":
        user["step"] = "username"
        update.message.reply_text("👤 اكتب username:")

    elif user["step"] == "username":
        context.user_data["new_user"] = text
        user["step"] = "password"
        update.message.reply_text("🔑 اكتب password:")

    elif user["step"] == "password":
        user["accounts"].append({
            "username": context.user_data["new_user"],
            "password": text,
            "balance": 0
        })

        user["step"] = None
        update.message.reply_text("✅ تم إنشاء الحساب")

    # -------- تعبئة/سحب --------
    elif text == "💳 تعبئة/سحب":
        accounts = user["accounts"]

        if not accounts:
            update.message.reply_text("❌ لا يوجد حسابات")
            return

        keyboard = [
            [InlineKeyboardButton(acc["username"], callback_data=f"select_{i}")]
            for i, acc in enumerate(accounts)
        ]

        update.message.reply_text("اختر الحساب:", reply_markup=InlineKeyboardMarkup(keyboard))

    elif user["step"] == "amount_account":
        try:
    user["amount"] = int(text)
except:
    update.message.reply_text("❌ أدخل رقم صحيح")
    return
        user["step"] = None

        keyboard = [
            [InlineKeyboardButton("➕ تعبئة", callback_data="deposit_acc")],
            [InlineKeyboardButton("➖ سحب", callback_data="withdraw_acc")]
        ]

        update.message.reply_text("اختر العملية:", reply_markup=InlineKeyboardMarkup(keyboard))

    # -------- إدخال مبلغ محفظة --------
    elif user["step"] == "deposit_wallet":
        user["amount"] = int(text)
        user["action"] = "deposit_wallet"
        user["step"] = None

        keyboard = [
            [InlineKeyboardButton("📱 سيريتيل", callback_data="syriatel")],
            [InlineKeyboardButton("📱 شام", callback_data="sham")]
        ]

        update.message.reply_text("اختر:", reply_markup=InlineKeyboardMarkup(keyboard))

    elif user["step"] == "withdraw_wallet":
        user["amount"] = int(text)
        user["action"] = "withdraw_wallet"
        user["step"] = None

        keyboard = [
            [InlineKeyboardButton("📱 سيريتيل", callback_data="syriatel")],
            [InlineKeyboardButton("📱 شام", callback_data="sham")]
        ]

        update.message.reply_text("اختر:", reply_markup=InlineKeyboardMarkup(keyboard))

    # -------- تغيير كلمة السر --------
    elif user["step"] == "change_pass":
        i = user["selected_account"]
        user["accounts"][i]["password"] = text
        user["step"] = None
        update.message.reply_text("✅ تم تغيير كلمة السر")

# ---------------- تشغيل ----------------
def main():
    updater = Updater(TOKEN, use_context=True)
    dp = updater.dispatcher

    dp.add_handler(CommandHandler("start", start))
    dp.add_handler(MessageHandler(Filters.text, handle_message))
    dp.add_handler(CallbackQueryHandler(button))

    updater.start_polling()
    updater.idle()

if __name__ == "__main__":
    main()
